
# SEO settings
title: "APC_"
title2: "LANCIS" # default: ""
description: "Área de Planeación Colaborativa de LANCIS"
keywords: "Lancis, Planeación, Colaborativa"
url:  # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics:
repo:
disqus_shortname: ""
twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "LANCIS_APC"
  job      : "Área de Planeación Colaborativa"
  bio      : "Área de Planeación Colaborativa del Laboratorio de Ciencias de la Sostenibilidad"
  thumb    : /images/author.png
  email    : hnrird@gmail.com
  url      : http://lancis-apc.github.io
  github   : http://github.com/lancis-apc
  twitter  :
  facebook :
  linkedin :

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site:

plugins: # (antes gems)
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
